//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteHocAVOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        public int IDCauHoi { get; set; }
        public string CauHoi1 { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public string DanAnDung { get; set; }
        public Nullable<int> ID_Category { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
